version: '3.7'

services:
  app:
    build: 
      dockerfile: ./Dockerfile
    environment:
      - PORT=3000
      - POSTGRES_HOST=d76120a33425
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE='fezinha'
      - POSTGRES_USER='fezinha'
      - POSTGRES_PASSWORD='password'
      - POSTGRES_ROOT_PASSWORD='password'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - 3030:3030
    networks:
      proxy-network:
        aliases:
          - app

  db:
    platform: linux/x86_64
    image: postgres
    environment:
      POSTGRES_DATABASE: 'fezinha'
      POSTGRES_USER: 'fezinha'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_ROOT_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    # volumes:
    #   - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"


networks:
  proxy-network:
    name: 'fezinha'
    driver: bridge
